.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

stages:
  - build
  - test

before_script:
 - Set-Variable -Name "time" -Value (date -Format "%H:%m")
 - echo ${time}
 - echo "started by ${GITLAB_USER_NAME}"

build:
  extends:
  - .shared_windows_runners
  image: mcr.microsoft.com/powershell7.0.2-nanoserver-1809-kb4561608-amd64
  stage: build
  script:
  - echo "running scripts in the build job"
  - powershell -File whichos.ps1
  - powershell -File build.ps1
  - powershell -Command "New-Item -Path . -ItemType Directory -Name '.public' -Force"
  - powershell -Command "Copy-Item -Path .\bin\*.exe -Destination .\public\ -Force"
  - powershell -Command "Rename-Item -Path .\.public -NewName .\public -Force"
  artifacts:
    paths:
    - public
  only:
  - docker-tests

test:
  extends:
  - .shared_windows_runners
  stage: test
  script:
  - echo "running scripts in the test job"
  - powershell -File whichos.ps1
  - powershell -File build.ps1
  - powershell -Command "New-Item -Path . -ItemType Directory -Name '.public' -Force"
  - powershell -Command "Copy-Item -Path .\bin\*.exe -Destination .\public\ -Force"
  - powershell -Command "Rename-Item -Path .\.public -NewName .\public -Force"
  artifacts:
    paths:
    - public
  only:
  - master
