image: philippheuer/docker-gitlab-powershell

stages:
  - build
  - test

build:
  stage: build
  script:
  # run PowerShell Command
  - powershell -Command "New-Item -Path . -ItemType Directory -Name '.public' -Force"
  # run PowerShell Script
  - powershell -File .\build.ps1
  # run PowerShell Commands
  - powershell -Command "Get-Date"
  - powershell -Command "Copy-Item -Path .\bin\*.exe -Destination .\public\ -Confirm:$false -Force"
  - powershell -Command "Rename-Item -Path .\.public -NewName .\public -Confirm:$false -Force"
  artifacts:
    paths:
    - public
  only:
  - docker-tests

build:
  stage: build
  script:
  # run PowerShell Command
  - powershell -Command "New-Item -Path . -ItemType Directory -Name '.public' -Force"
  # run PowerShell Script
  - powershell -File .\build.ps1
  # run PowerShell Commands
  - powershell -Command "Get-Date"
  - powershell -Command "Copy-Item -Path .\bin\*.exe -Destination .\public\ -Confirm:$false -Force"
  - powershell -Command "Rename-Item -Path .\.public -NewName .\public -Confirm:$false -Force"
  artifacts:
    paths:
    - public
  only:
  - master