image:
  - Visual Studio 2017
clone_folder: c:\projects\software-matrix
platform:
  - x64
build: false
version: 4.2.4.{build}
init:
  - git config --global core.autocrlf true
  - ps: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
install:
  - ps: |
      [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
      Install-PackageProvider -Name NuGet -Force
      Install-Module -Name PowerShellGet -Force
      Install-Module -Name PSSQLite -Force
      Install-Module -Name PS2EXE -Force
      Install-Module -Name SpeedTester
      Import-Module -Name SpeedTester
      Import-Module -Name PSSQLite
      Start-SpeedTest -UploadMB 30 -DownloadMB 30
      "Git version: $(git.exe --version)"
      "PSVersion:   $($PSVersionTable.PSVersion)"
      "PSBuild:     $($PSVersionTable.BuildVersion)"
      "clr version: $($PSVersionTable.ClrVersion)"
      "Host name:   $($Host.Name)"
build_script:
- ps: |
    Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
    c:\projects\software-matrix/lib/scripts/Test-Manifests.ps1
#test_script:
#- ps: ./test/appveyor/test.ps1
on_finish:
- ps: |
    Write-Host "Running RDP"
    $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
