$qb=Invoke-CreateCManiCore -Category browser `
                           -Publisher 'Mozilla' `
                           -Name 'Firefox' `
                           -Version '78.0.2' `
                           -CopyrightNotice "Copyright $([char]0x00A9) 1998-2020 Mozilla Foundation" `
                           -License 'MPL-2.0' `
                           -LicenseURI 'https://www.mozilla.org/en-US/MPL/' `
                           -Tags @('firefox','browser','mozilla') `
                           -Description 'Bringing together all kinds of awesomeness to make browsing better for you.' `
                           -Homepage 'https://www.mozilla.org/en-US/firefox/new/' `
                           -Arch @('x64','x86') `
                           -Languages @('en-US','en-GB','en-CA') `
                           -HasNuspec $true `
                           -NuspecFile 'https://raw.githubusercontent.com/chocolatey-community/chocolatey-coreteampackages/master/automatic/firefox/firefox.nuspec' `
                           -Depends @() `
                           -InstallURI_x64 @('https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=en-US','https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=en-GB','https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=en-CA') `
                           -InstallURI_x86 @('https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win&lang=en-US','https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win&lang=en-GB','https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win&lang=en-CA') `
                           -MsiExe_x64 @('msi','exe','msi') `
                           -MsiExe_x86 @('msi','msi','msi') `
                           -InstallExe_x64 @('firefox-x64-US.msi','firefox-x64-GB.msi','firefox-x64-CA.msi') `
                           -InstallExe_x86 @('firefox-US.msi','firefox-GB.msi','firefox-CA.msi') `
                           -InstallArgs_x64 @('/qn','/qn','/qn') `
                           -InstallArgs_x86 @('/qn','/qn','/qn') `
                           -UninstallExe_x64 @('C:\Program Files\Mozilla Firefox\uninstall\helper.exe','C:\Program Files\Mozilla Firefox\uninstall\helper.exe','C:\Program Files\Mozilla Firefox\uninstall\helper.exe') `
                           -UninstallExe_x86 @('1','2','3') `
                           -UninstallArgs_x64 @('/S','/S','/S') `
                           -UninstallArgs_x86 @('v','d','w') `
                           -UpdateURI_x64 'https://www.mozilla.org/en-US/firefox/releasenotes/' `
                           -UpdateURI_x86 @('https://www.mozilla.org/en-US/firefox/releasenotes/','https://www.mozilla.org/en-US/firefox/releasenotes/','https://www.mozilla.org/en-US/firefox/releasenotes/') `
                           -UpdateRegex_x64 @('<div class=\"c-release-version\">([\\d.]+)</div>','<div class=\"c-release-version\">([\\d.]+)</div>','<div class=\"c-release-version\">([\\d.]+)</div>') `
                           -UpdateRegex_x86 @('<div class=\"c-release-version\">([\\d.]+)</div>','<div class=\"c-release-version\">([\\d.]+)</div>','<div class=\"c-release-version\">([\\d.]+)</div>')
$qb