version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: C:\circle_ci_build_dir
    branches:
      only:
        - master
        - ci/circleci-tests
    size: medium
    steps:
      - checkout
      - run: systeminfo
      - run: 
          name: "System Info"
          command: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run hello-world:nanoserver-1809
      - run:
          name: "Install VLC"
          shell: powershell.exe
          command: |
            choco install vlc
            Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -like "*Video*"} | Select-Object Name,Version
      - run:
          name: "install powershell core"
          command: dotnet tool install --global PowerShell
      - run:
          name: "pscore version table"
          command: |
            pwsh $PSVersionTable
