name: CI Testing

on:
  push:
    branches:
      - ci/*
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Display environment variables
      run: |
        "Git version: $(git.exe --version)"
        "PSVersion:   $($PSVersionTable.PSVersion), build: $($PSVersionTable.BuildVersion), clr version: $($PSVersionTable.ClrVersion)"
        "Host name:   $($Host.Name)"
        $Env:PATH
      shell: powershell
    - name: Bootstrap setup
      run: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force
        Install-Module -Name PowerShellGet -Force
      shell: pwsh
    - name: Install required modules
      run: |
        Install-Module -Name Get.URLStatusCode
        Install-Module -Name GetRedirectedURL
      shell: pwsh
    - name: Load CMani
      run: |
        . .\cmani_core-edition.ps1
      shell: pwsh
    - name: Build scripts
      run: |
        Get-ChildItem -Path .\tests -Filter "test_func-*.ps1" | ForEach-Object { & $_.FullName }
      shell: pwsh
    - name: Install/Uninstall applications
      run: |
        Write-Output 'No install on Ubuntu'
#       .\tests\test-install.ps1
      shell: pwsh
  windows-pscore:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Display environment variables
      run: |
        "Git version: $(git.exe --version)"
        "PSVersion:   $($PSVersionTable.PSVersion), build: $($PSVersionTable.BuildVersion), clr version: $($PSVersionTable.ClrVersion)"
        "Host name:   $($Host.Name)"
        $Env:PATH
      shell: powershell
    - name: Bootstrap setup
      run: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force
        Install-Module -Name PowerShellGet -Force
      shell: pwsh
    - name: Install required modules
      run: |
        Install-Module -Name Get.URLStatusCode
        Install-Module -Name GetRedirectedURL
      shell: pwsh
    - name: Load CMani
      run: |
        . .\cmani_core-edition.ps1
      shell: pwsh
    - name: Build scripts
      run: |
        Get-ChildItem -Path .\tests -Filter "test_func-*.ps1" | ForEach-Object { & $_.FullName }
      shell: pwsh
    - name: Install/Uninstall applications
      run: |
        .\tests\test-install.ps1
      shell: pwsh
  windows-psdesktop:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Display environment variables
      run: |
        "Git version: $(git.exe --version)"
        "PSVersion:   $($PSVersionTable.PSVersion), build: $($PSVersionTable.BuildVersion), clr version: $($PSVersionTable.ClrVersion)"
        "Host name:   $($Host.Name)"
        $Env:PATH
      shell: powershell
    - name: Bootstrap setup
      run: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force
        Install-Module -Name PowerShellGet -Force
      shell: pwsh
    - name: Install required modules
      run: |
        Install-Module -Name Get.URLStatusCode
        Install-Module -Name GetRedirectedURL
      shell: pwsh
    - name: Load CMani
      run: |
        . .\cmani_core-edition.ps1
      shell: pwsh
    - name: Build scripts
      run: |
        Get-ChildItem -Path .\tests -Filter "test_func-*.ps1" | ForEach-Object { & $_.FullName }
      shell: pwsh
    - name: Install/Uninstall applications
      run: |
        .\tests\test-install.ps1
      shell: pwsh